name: Scan Unused Files

on:
  schedule:
    - cron: "0 0 * * 0"         # Runs every Sunday
  workflow_dispatch:             # Allows manual run

jobs:
  run:
    uses: Sumit4545270/.github/.github/workflows/unused-files.yml@main
